### ISSUE TITLE
Picking new tracks in Music and Podcast apps cause error

### ISSUE THREAD

**Issue by jedgarpark** [adafruit/Adafruit_CircuitPython_BLE_Apple_Media#3]
With CPB paired and ble_apple_media_simpletest.py running, outputting messages to REPL, there is an error thrown when picking new tracks by name (not with >> button):
`Traceback (most recent call last):
  File "code.py", line 33, in <module>
  File "/lib/adafruit_ble_apple_media.py", line 106, in __get__
  File "/lib/adafruit_ble_apple_media.py", line 100, in _update
RuntimeError: packet too short`

This is with the iOS native default Music app and Podcast app.

Same error is also thrown when you close the Music app, even if no music is currently playing.

This does not happen in Spotify. This does not happen if the track ends and moves to the next track on its own, either.

**Comment by evaherrada** [comment]
@jedgarpark I'm getting the same issue when pausing music in Tidal (haven't tested in other apps). Probably the same root cause but I'll open a different issue

Edit: Just remembered something. I did not having any issues doing what you described here in Tidal, so based on my extremely scientific study (n=1) this doesn't happen in Tidal.

**Comment by evaherrada** [comment]
@jedgarpark Are you on the most recent version? I was having a similar issue and updating the app solved it.

**Comment by jedgarpark** [comment]
@dherrada updating which app solved it?

**Comment by evaherrada** [comment]
@jedgarpark updating Tidal temporarily solved it. I think I don’t have the most recent version of this library so I’ll try getting the most recent version and giving it a go.

**Comment by kattni** [comment]
@jedgarpark Are you still experiencing this issue?

**Comment by jedgarpark** [comment]
worse. 
`File "adafruit_ble/__init__.py", line 143, in pair _bleio.SecurityError" Unspecified issues. Can be that the pairing propmpt in the other device was declined or ignored.`

**Comment by evaherrada** [comment]
@jedgarpark When I was doing pyloton, I had to add a try/except, excepting RuntimeError and UnicodeError to the part of my code that read the data from the iphone. Not sure if that will work for you or if you're even still having the same issue since the error message changed, Here's the whole function:

```    
    def read_ams(self):
        """
        Reads data from AppleMediaServices
        """
        current = time.time()
        try:
            if current - self.start > 3:
                self.track_artist = not self.track_artist
                self.start = time.time()
            if self.track_artist:
                data = self.ams.artist
            if not self.track_artist:
                data = self.ams.title
        except (RuntimeError, UnicodeError):
            data = None
 
        if data:
            data = data[:16] + (data[16:] and '..')
 
        return data
```
